### ISSUE TITLE
LineageOS 15.1 kernel compilation error

### ISSUE THREAD

**Issue by SharkEzz** [ananjaser1211/Refinedkernel_2#5]
Hello !

I try for a few days to build LineageOS 15.1 from the source now that all proprietary blobs are available.
My problem is: you have to get the kernel source code in order to build LineageOS, to do this, I cloned the RefinedKernel_2 git on the branch 'aosp' then I put the source code inside the LOS directory (kernel/samsung/j5y17lte), but, when I launch the build, all goes well until I encounter an error when compiling the kernel about a certain file (firmware/tsp_imagis/ist3038h_a3x.fw.ihex) so the compilation stop here and the build fail.
I tried to replace these files (then the whole directory) with those of the stock kernel but no improvement.
If you have an idea about how to fix this issue I'd be happy to hear it!

PS: If you want any screenshot of the error, I can give you that.

Thank you in advance for your help !

**Comment by ananjaser1211** [comment]
Hey. yes its a known error, due to missing firmware files. you can either try to fix it by using prebuilt ihex files from J5 source or (what im doing) https://github.com/Mohi1117/android_kernel_samsung_exynos7870
add J5 support to that kernel, so J5 DTS CONFIG and so on, merge new changes that are required by LOS (NP Filter , new binder and so on) and in the device tree (on my organization) point it at the new config. just be sure when cloning the tree BEFORE the edits ive done to support AEX (i can only sync AEX so i cant compile LOS yet) 

Goodluck

**Comment by SharkEzz** [comment]
Ok so...
I finally went to try to compile Aosp Extended because I had too many problems with LineageOS.

In order to build AEX I switched on your device tree (the one that supports AEX). Everything was going well the compilation was almost over BUT I had an error about dex2oat telling me this: "not a valid memory value, or not divisible by 1024" and I saw that actually the values "-Xmx" and "- Xms" have no value assigned (see the screenshot below). After some search on Google, I saw that it was apparently a device tree problem but I could not find more information about this.

Sorry to bother you with my compilation problems but do you have an idea about how to solve this problem ?

Again, thank you for your help !

![dex2oat](https://user-images.githubusercontent.com/27637158/37565521-279fe2b4-2aab-11e8-8dec-aec3c2b9b0a9.png)

**Comment by ananjaser1211** [comment]
Might need to edit system.prop and add -xms and dalvik values from stock build prop. I'm trying to get a server to compile it :/

**Comment by SharkEzz** [comment]
Tried what you said but no changes I have the same issue. Maybe I missed something?

Here is my system.prop with Xms/Xmx added : 

![system prop dalvik](https://user-images.githubusercontent.com/27637158/37569347-44a6245a-2ae1-11e8-91b5-0d9d477c8a28.png)

**Comment by ananjaser1211** [comment]
Hmm, that looks right. not sure why its not working. ill check it out when i compile AEX as i have no clue at the moment.
